apiVersion: core.choreo.dev/v1alpha1
kind: Component
metadata:
  name: backend
spec:
  type: Service
  source:
    git:
      url: https://github.com/YOUR_GITHUB_USERNAME/Choose-Your-Own-Adventur
      branch: main
      path: backend
  endpoints:
    - name: http
      type: REST
      service:
        port: 8000
